[package]
name = "minimum-browser"
version = "0.1.0"
authors = ["Ubugeeei"]
edition = "2018"

[[cdylib]]
name = "html_parser"
path = "src/html.rs"
[[cdylib]]
name = "dom_definition"
path = "src/dom.rs"

[dependencies]
combine = "4.6.0"