[package]
name = "minimum-browser"
version = "0.1.0"
authors = ["Ubugeeei"]
edition = "2018"

[[cdylib]]
name = "html_parser_modules"
path = "src/html_parser/mod.rs"
[[cdylib]]
name = "dom_definition"
path = "src/html_parser/dom.rs"
[[cdylib]]
name = "parse_attributes"
path = "src/html_parser/parse_attributes.rs"
[[cdylib]]
name = "parse_tags"
path = "src/html_parser/parse_tag.rs"

[dependencies]
combine = "4.6.0"