[package]
name = "kurt"
version = "0.1.0"
authors = ["Ubugeeei"]
edition = "2018"

[dependencies]
thiserror = "1.0"
combine = "4.5.2"
glasper = { git = "https://github.com/Ubugeeei/Glasper.git" }
gtk = { version = "0.4.8", package = "gtk4" }