name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: install_dependencies
      run: |
        sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu `lsb_release -sc` main universe restricted multiverse"
        sudo apt-get update -y -qq
        sudo apt-get install libsdl2-dev
    - uses: actions/checkout@v3
    - name: Check Format
      run: cargo fmt --check
    - name: Lint
      run: cargo clippy --all-targets --all-features --
    - name: Build
      run: cargo build --release
    - name: Run tests
      run: cargo test
